### ISSUE TITLE
Correção Exercício `0.7.1`

### ISSUE THREAD

**Issue by mathiasgheno** [mairyeduardo/IconsDWI#1]
# Correção Exercício `0.7.1`

> Você deve implementar o equivalente ao três botões existentes la lateral direita da barra de navegação do facebook. Você deve fazer uso do Positioned Layout para o badge de notificações e também para o indicativo de dropdown para o botão do perfil do usuário. O dropdown não precisa ser implementado, apenas a posição dos elementos. O conteúdo pode ficar centralizado. Não esqueça de fazer uso do conteúdo apresentado na aula passada (combinação de seletores, adição de ícones, variáveis CSS) para a entrega desse exercício. Você não precisa fazer uso de uma imagem no último ítem..  [Referência visual](https://i.imgur.com/l2XgANK.png).

Faltou a criação do badge de notificação de faltou deixar o seu ultimo ícone mais arredondado.  Além disso, faltou fazer uso da funcionalidade das variáveis CSS. 

Para atingir o primeiro item, bastaria criar um `span` dentro do `botaoprincipal`. 

```css
.botaoprincipal span {
   position: absolute;
   width: 15px;
   height: 15px;
   background-color: red;
   color: white;
   border-radius: 50%;
   top: 5px;
   right: 5px;
}
```

```html
<button class="botaoprincipal">
    <span>9+</span>
    <svg class="svg1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
        <path
            d="M224 0c-17.7 0-32 14.3-32 32V51.2C119 66 64 130.6 64 208v18.8c0 47-17.3 92.4-48.5 127.6l-7.4 8.3c-8.4 9.4-10.4 22.9-5.3 34.4S19.4 416 32 416H416c12.6 0 24-7.4 29.2-18.9s3.1-25-5.3-34.4l-7.4-8.3C401.3 319.2 384 273.9 384 226.8V208c0-77.4-55-142-128-156.8V32c0-17.7-14.3-32-32-32zm45.3 493.3c12-12 18.7-28.3 18.7-45.3H224 160c0 17 6.7 33.3 18.7 45.3s28.3 18.7 45.3 18.7s33.3-6.7 45.3-18.7z" />
    </svg>
</button>
```

Para o segundo item, bastaria definir uma altura para o `botaopequeno`. 

```css
.botaopequeno {
    width: 20px;
    height: 20px;
    padding: 0;
    margin: 0;
}
```

**Nota:** 6

# Comentários

https://github.com/mairyeduardo/IconsDWI/blob/393944aab132b29581508bb51542a9dc882cb333/index.html#L37-L42

Note que faltou fechar a sua tag `svg`.
